package com.KAC.vikranthpublications.model

data class OutdatedDataClass(val uniqueKey: String? = null,
                             val userid: String? = null,
                             val task_generated_date: String? = null,
                             val school_name: String? = null,
                             val school_email: String? = null,
                             val school_phone_number: String? = null,
                             val school_address: String? = null,
                             val school_pincode: String? = null,
                             val no_of_students: String? = null,
                             val contact_person_name: String? = null,
                             val contact_person_phone: String? = null,
                             val contact_person_email: String? = null,
                             val desicion_maker_name: String? = null,
                             val desicion_maker_phone: String? = null,
                             val desicion_maker_email: String? = null,
                             val desicion_maker_designation: String? = null,
                             val current_supplier: String? = null,
                             val current_supplier_discount_percentage: String? = null,
                             val prospect: String? = null,
                             val status: String? = null,
                             val follow_up_date: String? = null,
                             val follow_up_timestamp: String? = null,
                             val ttime: String? = null)
